# Generated by Django 4.0.2 on 2022-02-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=25)),
                ('usePurpose', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='testImg',
        ),
    ]
