# Generated by Django 4.0.2 on 2022-02-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEhome', '0002_baseprofile_delete_testimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
