# Generated by Django 4.0.2 on 2022-02-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEhome', '0004_alter_baseprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImg', models.ImageField(default='default.jpg', upload_to='user_profile')),
                ('address', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=100)),
                ('pincode', models.IntegerField(max_length=6)),
                ('bpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEhome.baseprofile')),
            ],
        ),
    ]
