# Generated by Django 4.0.2 on 2022-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEhome', '0005_fullprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullprofile',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
